AWSTemplateFormatVersion: '2010-09-09'
Description: 'Register Development Environment Launch Templates to AWS Service Catalog'

Parameters:
  ProjectTag:
    Type: String
    Default: AgentDevEnv
    Description: Project tag value for all resources
  
  ManagedByTag:
    Type: String
    Default: Administrator
    Description: ManagedBy tag value for all resources

Resources:
  # Configurable Development Environment Product
  DevEnvironmentProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: Development Environment
      Description: Configurable development environment with selectable instance type
      Owner: !ImportValue AgentDevEnv-PortfolioOwner
      ProvisioningArtifactParameters:
        - Name: v1.0
          Description: Initial version
          Info:
            LoadTemplateFromURL: !Sub 
              - 'https://${ArtifactBucket}.s3.${AWS::Region}.amazonaws.com/templates/dev-environment-template.yaml'
              - ArtifactBucket: !ImportValue AgentDevEnv-ArtifactBucketName
      Tags:
        - Key: Project
          Value: !Ref ProjectTag
        - Key: ManagedBy
          Value: !Ref ManagedByTag

  # Associate product with portfolio
  DevEnvironmentProductAssociation:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !ImportValue AgentDevEnv-PortfolioId
      ProductId: !Ref DevEnvironmentProduct

Outputs:
  DevEnvironmentProductId:
    Description: ID of the Development Environment Product
    Value: !Ref DevEnvironmentProduct
    Export:
      Name: AgentDevEnv-DevEnvironmentProductId
