AWSTemplateFormatVersion: '2010-09-09'
Description: 'Register Development Environment Launch Templates to AWS Service Catalog'

Parameters:
  ProjectTag:
    Type: String
    Default: AgentDevEnv
    Description: Project tag value for all resources
  
  ManagedByTag:
    Type: String
    Default: Administrator
    Description: ManagedBy tag value for all resources

Resources:
  # IAM Role for Service Catalog Launch Constraint
  ServiceCatalogLaunchRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: servicecatalog.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ServiceCatalogLaunchPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:*
                  - ec2:*
                  - iam:PassRole
                  - iam:GetRole
                  - iam:CreateRole
                  - iam:DeleteRole
                  - s3:GetObject
                  - servicecatalog:*
                  - ssm:*
                Resource: '*'
      Path: /
      Tags:
        - Key: Project
          Value: !Ref ProjectTag
        - Key: ManagedBy
          Value: !Ref ManagedByTag

  # Configurable Development Environment Product
  DevEnvironmentProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: Development Environment
      Description: Configurable development environment with selectable instance type
      Owner: !ImportValue AgentDevEnv-PortfolioOwner
      ProvisioningArtifactParameters:
        - Name: v1.1
          Description: Initial version
          Info:
            LoadTemplateFromURL: !Sub 
              - 'https://${ArtifactBucket}.s3.${AWS::Region}.amazonaws.com/templates/dev-environment-template.yaml'
              - ArtifactBucket: !ImportValue AgentDevEnv-ArtifactBucketName
      Tags:
        - Key: Project
          Value: !Ref ProjectTag
        - Key: ManagedBy
          Value: !Ref ManagedByTag

  # Associate product with portfolio
  DevEnvironmentProductAssociation:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !ImportValue AgentDevEnv-PortfolioId
      ProductId: !Ref DevEnvironmentProduct
      
  # Add launch role constraint to the product
  LaunchRoleConstraint:
    Type: AWS::ServiceCatalog::LaunchRoleConstraint
    DependsOn: DevEnvironmentProductAssociation
    Properties:
      PortfolioId: !ImportValue AgentDevEnv-PortfolioId
      ProductId: !Ref DevEnvironmentProduct
      RoleArn: !GetAtt ServiceCatalogLaunchRole.Arn
      Description: Launch role constraint for Development Environment product
      
  # Grant access to the portfolio for all users in the account
  PortfolioPrincipalAssociation:
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Properties:
      PortfolioId: !ImportValue AgentDevEnv-PortfolioId
      PrincipalARN: 'arn:aws:iam:::role/*'
      PrincipalType: IAM_PATTERN

Outputs:
  DevEnvironmentProductId:
    Description: ID of the Development Environment Product
    Value: !Ref DevEnvironmentProduct
    Export:
      Name: AgentDevEnv-DevEnvironmentProductId
      
  ServiceCatalogLaunchRoleArn:
    Description: ARN of the Service Catalog Launch Role
    Value: !GetAtt ServiceCatalogLaunchRole.Arn
    Export:
      Name: AgentDevEnv-ServiceCatalogLaunchRoleArn
