AWSTemplateFormatVersion: '2010-09-09'
Description: 'Main Administrator Setup Template for Development Environment'

Parameters:
  ProjectTag:
    Type: String
    Default: DevelopmentEnv
    Description: Project tag value for all resources
  
  ManagedByTag:
    Type: String
    Default: Administrator
    Description: ManagedBy tag value for all resources

Resources:
  NetworkInfrastructureStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./01-admin-network-infrastructure.yaml
      TimeoutInMinutes: 30
      Parameters:
        ProjectTag: !Ref ProjectTag
        ManagedByTag: !Ref ManagedByTag
      Tags:
        - Key: Component
          Value: NetworkInfrastructure
        - Key: Project
          Value: !Ref ProjectTag
        - Key: ManagedBy
          Value: !Ref ManagedByTag

  AppManagerSetupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./02-admin-app-manager-setup.yaml
      TimeoutInMinutes: 20
      Parameters:
        ProjectTag: !Ref ProjectTag
        ManagedByTag: !Ref ManagedByTag
      Tags:
        - Key: Component
          Value: AppManager
        - Key: Project
          Value: !Ref ProjectTag
        - Key: ManagedBy
          Value: !Ref ManagedByTag
    DependsOn: NetworkInfrastructureStack

  PatchManagementStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./03-admin-patch-management.yaml
      TimeoutInMinutes: 15
      Parameters:
        ProjectTag: !Ref ProjectTag
        ManagedByTag: !Ref ManagedByTag
      Tags:
        - Key: Component
          Value: PatchManagement
        - Key: Project
          Value: !Ref ProjectTag
        - Key: ManagedBy
          Value: !Ref ManagedByTag
    DependsOn: NetworkInfrastructureStack

  MonitoringDashboardStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./04-admin-monitoring-dashboard.yaml
      TimeoutInMinutes: 10
      Parameters:
        ProjectTag: !Ref ProjectTag
        ManagedByTag: !Ref ManagedByTag
      Tags:
        - Key: Component
          Value: MonitoringDashboard
        - Key: Project
          Value: !Ref ProjectTag
        - Key: ManagedBy
          Value: !Ref ManagedByTag
    DependsOn: NetworkInfrastructureStack

Outputs:
  VpcId:
    Description: VPC ID
    Value: !GetAtt NetworkInfrastructureStack.Outputs.VpcId
    Export:
      Name: DevEnvironment-VpcId
  
  PrivateSubnet1Id:
    Description: Private Subnet 1 ID
    Value: !GetAtt NetworkInfrastructureStack.Outputs.PrivateSubnet1Id
    Export:
      Name: DevEnvironment-PrivateSubnet1Id
  
  PrivateSubnet2Id:
    Description: Private Subnet 2 ID
    Value: !GetAtt NetworkInfrastructureStack.Outputs.PrivateSubnet2Id
    Export:
      Name: DevEnvironment-PrivateSubnet2Id
  
  ApplicationId:
    Description: Application ID for DevEnvironment
    Value: !GetAtt AppManagerSetupStack.Outputs.ApplicationId
    Export:
      Name: DevEnvironment-ApplicationId
