AWSTemplateFormatVersion: '2010-09-09'
Description: 'Application Manager and Service Catalog Configuration for Development Environment'

Parameters:
  ProjectTag:
    Type: String
    Default: AgentDevEnv
    Description: Project tag value for all resources
  
  ManagedByTag:
    Type: String
    Default: Administrator
    Description: ManagedBy tag value for all resources
    
  PortfolioName:
    Type: String
    Default: Development Environment Portfolio
    Description: Name of the Service Catalog portfolio
  
  PortfolioDescription:
    Type: String
    Default: Portfolio containing development environment templates
    Description: Description of the Service Catalog portfolio
  
  PortfolioOwner:
    Type: String
    Default: IT Administrator
    Description: Owner of the Service Catalog portfolio

Resources:
  # Application Manager Configuration
  AgentDevEnvApplication:
    Type: AWS::ServiceCatalogAppRegistry::Application
    Properties:
      Name: AgentDevEnvApplication
      Description: Development Environment for Agents
      Tags:
        Environment: Development
        Project: !Ref ProjectTag
        ManagedBy: !Ref ManagedByTag

  # Create a resource group for the application
  AgentDevEnvResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: AgentDevEnvResourceGroup
      Description: Resource group for Agent Development Environment
      ResourceQuery:
        Type: TAG_FILTERS_1_0
        Query: 
          ResourceTypeFilters:
            - "AWS::AllSupported"
          TagFilters:
            - Key: Project
              Values:
                - !Ref ProjectTag
            - Key: ManagedBy
              Values:
                - !Ref ManagedByTag
      Tags:
        - Key: Project
          Value: !Ref ProjectTag
        - Key: ManagedBy
          Value: !Ref ManagedByTag
          
  ServiceCatalogPortfolio:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      DisplayName: !Ref PortfolioName
      Description: !Ref PortfolioDescription
      ProviderName: !Ref PortfolioOwner
      Tags:
        - Key: Project
          Value: !Ref ProjectTag
        - Key: ManagedBy
          Value: !Ref ManagedByTag

  # IAM Role for Service Catalog Launch Constraint
  ServiceCatalogLaunchRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: servicecatalog.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ServiceCatalogLaunchPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:*
                  - ec2:*
                  - iam:PassRole
                  - iam:GetRole
                  - iam:CreateRole
                  - iam:DeleteRole
                  - s3:GetObject
                  - servicecatalog:*
                  - ssm:*
                Resource: '*'
      Path: /
      Tags:
        - Key: Project
          Value: !Ref ProjectTag
        - Key: ManagedBy
          Value: !Ref ManagedByTag

  # Grant access to the portfolio for all users in the account
  PortfolioPrincipalAssociation:
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Properties:
      PortfolioId: !Ref ServiceCatalogPortfolio
      PrincipalARN: 'arn:aws:iam:::role/*'
      PrincipalType: IAM_PATTERN

Outputs:
  ApplicationId:
    Description: Application ID for AgentDevEnv
    Value: !GetAtt AgentDevEnvApplication.Id
    Export:
      Name: AgentDevEnv-ApplicationId
      
  PortfolioId:
    Description: ID of the Service Catalog Portfolio
    Value: !Ref ServiceCatalogPortfolio
    Export:
      Name: AgentDevEnv-PortfolioId
      
  PortfolioOwner:
    Description: Owner of the Service Catalog Portfolio
    Value: !Ref PortfolioOwner
    Export:
      Name: AgentDevEnv-PortfolioOwner

  ServiceCatalogLaunchRoleArn:
    Description: ARN of the Service Catalog Launch Role
    Value: !GetAtt ServiceCatalogLaunchRole.Arn
    Export:
      Name: AgentDevEnv-ServiceCatalogLaunchRoleArn
