AWSTemplateFormatVersion: '2010-09-09'
Description: 'Main Administrator Setup Template for Development Environment'

Parameters:
  ProjectTag:
    Type: String
    Default: DevelopmentEnv
    Description: Project tag value for all resources
  
  ManagedByTag:
    Type: String
    Default: Administrator
    Description: ManagedBy tag value for all resources

  PortfolioName:
    Type: String
    Default: Development Environment Portfolio
    Description: Name of the Service Catalog portfolio
  
  PortfolioDescription:
    Type: String
    Default: Portfolio containing development environment templates
    Description: Description of the Service Catalog portfolio
  
  PortfolioOwner:
    Type: String
    Default: IT Administrator
    Description: Owner of the Service Catalog portfolio
    
  ArtifactBucketName:
    Type: String
    Default: dev-environment-artifacts
    Description: Name of the S3 bucket for storing artifacts

Resources:
  NetworkInfrastructureStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./01-admin-network-infrastructure.yaml
      TimeoutInMinutes: 30
      Parameters:
        ProjectTag: !Ref ProjectTag
        ManagedByTag: !Ref ManagedByTag
      Tags:
        - Key: Project
          Value: !Ref ProjectTag
        - Key: ManagedBy
          Value: !Ref ManagedByTag
        - Key: Component
          Value: NetworkInfrastructure

  ServiceCatalogStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./02-admin-service-catalog-setup.yaml
      TimeoutInMinutes: 20
      Parameters:
        ProjectTag: !Ref ProjectTag
        ManagedByTag: !Ref ManagedByTag
        PortfolioName: !Ref PortfolioName
        PortfolioDescription: !Ref PortfolioDescription
        PortfolioOwner: !Ref PortfolioOwner
        ArtifactBucketName: !Ref ArtifactBucketName
      Tags:
        - Key: Project
          Value: !Ref ProjectTag
        - Key: ManagedBy
          Value: !Ref ManagedByTag
        - Key: Component
          Value: ServiceCatalog
    DependsOn: NetworkInfrastructureStack

  PatchManagementStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./03-admin-patch-management.yaml
      TimeoutInMinutes: 15
      Parameters:
        ProjectTag: !Ref ProjectTag
        ManagedByTag: !Ref ManagedByTag
      Tags:
        - Key: Project
          Value: !Ref ProjectTag
        - Key: ManagedBy
          Value: !Ref ManagedByTag
        - Key: Component
          Value: PatchManagement
    DependsOn: NetworkInfrastructureStack

  MonitoringDashboardStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./04-admin-monitoring-dashboard.yaml
      TimeoutInMinutes: 10
      Parameters:
        ProjectTag: !Ref ProjectTag
        ManagedByTag: !Ref ManagedByTag
      Tags:
        - Key: Project
          Value: !Ref ProjectTag
        - Key: ManagedBy
          Value: !Ref ManagedByTag
        - Key: Component
          Value: MonitoringDashboard
    DependsOn: NetworkInfrastructureStack

Outputs:
  # Network Infrastructure Outputs
  VpcId:
    Description: VPC ID
    Value: !GetAtt NetworkInfrastructureStack.Outputs.VpcId
    Export:
      Name: DevEnvironment-VpcId
  
  PrivateSubnet1Id:
    Description: Private Subnet 1 ID
    Value: !GetAtt NetworkInfrastructureStack.Outputs.PrivateSubnet1Id
    Export:
      Name: DevEnvironment-PrivateSubnet1Id
  
  PrivateSubnet2Id:
    Description: Private Subnet 2 ID
    Value: !GetAtt NetworkInfrastructureStack.Outputs.PrivateSubnet2Id
    Export:
      Name: DevEnvironment-PrivateSubnet2Id
  
  # Service Catalog Outputs
  PortfolioId:
    Description: Service Catalog Portfolio ID
    Value: !GetAtt ServiceCatalogStack.Outputs.PortfolioId
    Export:
      Name: DevEnvironment-PortfolioId
  
  ArtifactBucketArn:
    Description: Artifact S3 Bucket ARN
    Value: !GetAtt ServiceCatalogStack.Outputs.ArtifactBucketArn
    Export:
      Name: DevEnvironment-ArtifactBucketArn
  
  # Patch Management Outputs
  PatchBaselineId:
    Description: Patch Baseline ID
    Value: !GetAtt PatchManagementStack.Outputs.PatchBaselineId
    Export:
      Name: DevEnvironment-PatchBaselineId
  
  MaintenanceWindowId:
    Description: Maintenance Window ID
    Value: !GetAtt PatchManagementStack.Outputs.MaintenanceWindowId
    Export:
      Name: DevEnvironment-MaintenanceWindowId
  
  # Monitoring Dashboard Outputs
  DashboardName:
    Description: CloudWatch Dashboard Name
    Value: !GetAtt MonitoringDashboardStack.Outputs.DashboardName
    Export:
      Name: DevEnvironment-DashboardName
